# Generated by Django 4.1.4 on 2022-12-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_complete_order_is_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_done',
            new_name='is_checked_out',
        ),
    ]
