# Generated by Django 4.1.4 on 2022-12-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_is_done_order_is_checked_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date_added',
        ),
    ]
