# Generated by Django 4.1.4 on 2022-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_address_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_orderd',
            field=models.DateTimeField(null=True),
        ),
    ]
