# Generated by Django 4.1.4 on 2022-12-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='carriage_code',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='seat_number',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
