# Generated by Django 4.1.4 on 2022-12-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_address_carriage_code_alter_address_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
