# Generated by Django 4.1.4 on 2023-01-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_address_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_orderd',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
