# Generated by Django 4.1.4 on 2023-01-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_order_date_orderd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orderd',
            new_name='date_ordered',
        ),
    ]
